[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
evm_version = 'shanghai'
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/',
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@prb/math/=lib/prb-math/src/',
]