services:
  launcher:
    build: ./launcher
    network_mode: host
    depends_on: ["web"]
    image: gcr.io/sekaictf-2023/misc_re-remix-launcher:latest
  web:
    build: ./web 
    network_mode: host
    image: gcr.io/sekaictf-2023/misc_re-remix-web:latest
  nginx:
    build: ./nginx
    network_mode: host
    image: gcr.io/sekaictf-2023/misc_re-remix-nginx:latest
