[package]
name = "chall"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "chall"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[profile.release]
overflow-checks = true
opt-level = 3
incremental = false
codegen-units = 1

[dependencies]
anchor-lang = { version = "0.28.0" }
